"""create drops table

Revision ID: 9ff006cdf27d
Revises: ff58d0d336e8
Create Date: 2026-08-19 18:31:31.487501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff006cdf27d'
down_revision: Union[str, Sequence[str], None] = 'ff58d0d336e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_views', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_drops_owner_id'), 'drops', ['owner_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_drops_token_hash'), 'drops', ['token_hash'], unique=True, schema='public')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', schema='auth', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='auth', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', schema='auth', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], source_schema='auth', ondelete='CASCADE')
    op.drop_index(op.f('ix_public_drops_token_hash'), table_name='drops', schema='public')
    op.drop_index(op.f('ix_public_drops_owner_id'), table_name='drops', schema='public')
    op.drop_table('drops', schema='public')
    # ### end Alembic commands ###
