"""add refresh tokens

Revision ID: ff58d0d336e8
Revises: 726811c7c2f9
Create Date: 2026-08-19 12:17:04.718817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff58d0d336e8'
down_revision: Union[str, Sequence[str], None] = '726811c7c2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS auth")
