MIB = 1024 * 1024
GIB = 1024 * MIB


# Guest limits
GUEST_MAX_FILES_PER_DROP = 1
GUEST_MAX_FILE_SIZE = 5 * MIB
GUEST_MAX_DROP_STORAGE = 5 * MIB


# Authenticated user limits
USER_MAX_FILES_PER_DROP = 5
USER_MAX_FILE_SIZE = 10 * MIB
USER_MAX_DROP_STORAGE = 20 * MIB
USER_MAX_ACTIVE_STORAGE = 30 * MIB


# Platform limits
PLATFORM_MAX_STORAGE = 1 * GIB


# Cleanup
FILE_CLEANUP_GRACE_MINUTES = 30
